### ISSUE TITLE
画面上部のメニューにマウスを乗せた時の表示がおかしい

### ISSUE THREAD

**Issue by kaichi1202** [kaichi1202/universe#2]
画面上部のメニューにマウスを乗せた時の背景の白い四角形の部分の大きさがおかしいです。

**Comment by kaichi1202** [comment]
現在bugfixにて修正中です。

**Comment by Kazaking** [comment]
ほーい

**Comment by Kazaking** [comment]
プルリクエストと同じような文じゃん

**Comment by kaichi1202** [comment]
修正が完了したのでcloseします。

---

@Kazaking 

> プルリクエストと同じような文じゃん

まあね
