### ISSUE TITLE
ファイルを圧縮する方法を発見しました

### ISSUE THREAD

**Issue by kaichi1202** [kaichi1202/universe#4]
ファイルを圧縮する方法を発見しました。

[参考リンク](http://logic.moo.jp/data/archives/513.html)

デプロイする時は是非使ってみてください。

**Comment by kaichi1202** [comment]
確認&コメントお願いします。

**Comment by miyakin1028** [comment]
おお！すごｗ

**Comment by kaichi1202** [comment]
@miyakin1028

**Comment by kaichi1202** [comment]
間違えてcloseしてしまったので直しました。

**Comment by kaichi1202** [comment]
とりあえずcloseします。デプロイする時にまたご覧ください。

**Comment by kaichi1202** [comment]
いろいろな圧縮系サービスのリンクをまとめているサイトがありました。

[URL](http://zxcvbnmnbvcxz.com/web-compression/)

universeがwebサーバーの容量を"超えてしまった時"に使ってください。
(超えてない時に使っても編集するのが面倒臭くなるだけだと思いますw)

**Comment by kaichi1202** [comment]
closeします。
